Repository dusk-network/rusk, pull requests merged in 2020-09, with the labels that each got.

#82 Pki service implementation
  Cargo.toml
  schema/basic_fields.proto
  schema/bid.proto
  schema/blindbid.proto
  schema/echo.proto
  schema/keys.proto
  schema/proto_tmp/rusk.proto
  schema/rusk.proto
  schema/transaction.proto
  src/lib/encoding.rs
  src/lib/lib.rs
  src/lib/services.rs
  src/lib/services/echoer.rs
  src/lib/services/pki.rs
  src/lib/services/pki/keygen.rs
  src/lib/services/pki/stealth_gen.rs
Labels: area:IPC, type:feature

#86 Update the rusk-schema subtree
  schema/basic_fields.proto
  schema/bid.proto
  schema/stake.proto
  schema/transfer.proto
Labels: area:IPC, type:refactor

#88 Update the rusk-schema subtree
  schema/rusk.proto
  schema/stake.proto
Labels: area:IPC

#92 Update rusk-schema subtree
  schema/transaction.proto
Labels: area:IPC

#98 Fix copyright headers
  build.rs
  contracts/bid/circuits/src/lib.rs
  contracts/bid/src/lib.rs
  contracts/transfer/src/lib.rs
  src/bin/main.rs
  src/bin/unix.rs
  src/bin/version.rs
  src/lib/encoding.rs
  src/lib/lib.rs
  src/lib/services.rs
  src/lib/services/echoer.rs
  src/lib/services/pki.rs
  src/lib/services/pki/keygen.rs
  src/lib/services/pki/stealth_gen.rs
  tests/echo_service_tests.rs
  tests/unix.rs
Labels: area:conf&build, type:refactor

#96 Migrate CI to Github Actions
  .github/workflows/dusk_ci.yml
  .travis.yml
  build.rs
  contracts/bid/circuits/src/lib.rs
  contracts/bid/src/lib.rs
  contracts/transfer/src/lib.rs
  src/bin/main.rs
  src/bin/unix.rs
  src/bin/version.rs
  src/lib/encoding.rs
  src/lib/lib.rs
  src/lib/services.rs
  src/lib/services/echoer.rs
  src/lib/services/pki.rs
  src/lib/services/pki/keygen.rs
  src/lib/services/pki/stealth_gen.rs
  tests/echo_service_tests.rs
  tests/unix.rs
Labels: area:conf&build, type:rfc

#99 Implement a circuit for the bid correctness proof
  Makefile
  contracts/bid/circuits/Cargo.toml
  contracts/bid/circuits/src/correctness.rs
  contracts/bid/circuits/src/lib.rs
Labels: area:cryptography, type:feature
