Repository dusk-network/rusk, pull requests merged in 2020-10, with the labels that each got.

#104 Compile bid correctness proof circuit in build time
  Cargo.toml
  build.rs
  contracts/bid/circuits/Cargo.toml
Labels: area:conf&build, area:cryptography, type:feature

#80 Implement Blindbid service for Rusk server
  .gitignore
  Cargo.toml
  Makefile
  build.rs
  src/lib/circuit_helpers.rs
  src/lib/encoding.rs
  src/lib/lib.rs
  src/lib/services.rs
  src/lib/services/blindbid.rs
  src/lib/services/blindbid/score_gen_handler.rs
  src/lib/services/blindbid/verify_score_handler.rs
  tests/blindbid_service.rs
  tests/echo_service_tests.rs
  tests/encoding.rs
Labels: area:IPC, area:block-generation, area:cryptography, type:feature

#117 Optimize & Speed Up Pub Params usage/read
  Cargo.toml
  src/lib/lib.rs
  src/lib/services/blindbid/score_gen_handler.rs
  src/lib/services/blindbid/verify_score_handler.rs
Labels: type:performance, type:refactor

#118 Add PKI and blind bid service to rusk server
  src/bin/main.rs
  src/lib/lib.rs
  src/lib/services/pki.rs
Labels: type:tech-debt

#119 Add tests for PKI service
  src/lib/encoding.rs
  src/lib/lib.rs
  src/lib/services/pki.rs
  tests/pki_service.rs
Labels: type:tech-debt

#121 Update bid_circuits & blindbid circuits aligned to the new Circuit trait
  build.rs
  contracts/bid/circuits/Cargo.toml
  contracts/bid/circuits/src/correctness.rs
  src/lib/services/blindbid/score_gen_handler.rs
  src/lib/services/blindbid/verify_score_handler.rs
Labels: area:cryptography, type:refactor

#122 Add `.rusk` profile folder with local / CI caching
  .github/workflows/dusk_ci.yml
  Cargo.toml
  build.rs
  contracts/bid/circuits/Cargo.toml
  contracts/bid/circuits/src/correctness.rs
  profile/Cargo.toml
  profile/src/lib.rs
  rustfmt.toml
  src/bin/main.rs
  src/bin/version.rs
  src/lib/lib.rs
  src/lib/services/blindbid.rs
  src/lib/services/blindbid/score_gen_handler.rs
  src/lib/services/blindbid/verify_score_handler.rs
  src/lib/services/echoer.rs
  tests/blindbid_service.rs
  tests/echo_service_tests.rs
  tests/pki_service.rs
Labels: area:architecture, type:feature, type:refactor

#93 Add transaction module
  Cargo.toml
  build.rs
  contracts/bid/circuits/Cargo.toml
  contracts/bid/circuits/src/correctness.rs
  src/lib/encoding.rs
  src/lib/lib.rs
  src/lib/proof.bin
  src/lib/services/blindbid/score_gen_handler.rs
  src/lib/services/blindbid/verify_score_handler.rs
  src/lib/transaction.rs
Labels: area:IPC, area:tx, type:feature

#83 Implement the dusk contract circuits
  contracts/transfer/circuits/Cargo.toml
  contracts/transfer/circuits/src/dusk_contract.rs
  contracts/transfer/circuits/src/dusk_contract/execute.rs
  contracts/transfer/circuits/src/dusk_contract/send_to_contract_obfuscated.rs
  contracts/transfer/circuits/src/dusk_contract/send_to_contract_transparent.rs
  contracts/transfer/circuits/src/dusk_contract/withdraw_from_obfuscated.rs
  contracts/transfer/circuits/src/dusk_contract/withdraw_from_obfuscated_to_contract.rs
  contracts/transfer/circuits/src/gadgets/balance.rs
  contracts/transfer/circuits/src/gadgets/merkle.rs
  contracts/transfer/circuits/src/gadgets/nullifier.rs
  contracts/transfer/circuits/src/gadgets/preimage.rs
  contracts/transfer/circuits/src/gadgets/range.rs
  contracts/transfer/circuits/src/gadgets/secret_key.rs
  contracts/transfer/circuits/src/lib.rs
Labels: area:cryptography, type:feature
