Repository dusk-network/rusk, pull requests merged in 2020-08, with the labels that each got.

#67 MVI rusk
  .travis.yml
  Cargo.toml
  Makefile
  build.rs
  proto_tmp/rusk.proto
  src/bin/main.rs
  src/bin/version.rs
  src/client.rs
  src/lib/lib.rs
  src/lib/services.rs
  src/lib/services/echoer.rs
  src/main.rs
  src/server.rs
  src/test_contract_transfer.rs
  tests/echo_service_tests.rs
Labels: area:architecture, area:testing, type:refactor

#71 Add schema subtree
  schema/.gitignore
  schema/LICENSE
  schema/README.md
Labels: area:conf&build

#72 Schema integration
  build.rs
  schema/.gitignore
  schema/echo.proto
  schema/proto_tmp/rusk.proto
  schema/rusk.proto
  src/bin/main.rs
  src/lib/services/echoer.rs
  tests/echo_service_tests.rs
Labels: type:feature, type:refactor

#74 Define modular structure for rusk contracts.
  contracts/bid/Cargo.toml
  contracts/bid/circuits/Cargo.toml
  contracts/bid/circuits/rustfmt.toml
  contracts/bid/circuits/src/lib.rs
  contracts/bid/rustfmt.toml
  contracts/bid/src/lib.rs
  contracts/transfer/circuits/Cargo.toml
  contracts/transfer/circuits/rustfmt.toml
  contracts/transfer/circuits/src/lib.rs
Labels: area:conf&build

#75 Support UDS & TCP/IP for ipc
  .travis.yml
  Cargo.toml
  Makefile
  src/bin/main.rs
  src/bin/unix.rs
  tests/echo_service_tests.rs
  tests/unix.rs
Labels: area:IPC, type:refactor
