Repository dusk-network/rusk, pull requests merged in 2020-12, with the labels that each got.

#133 Refactor dependencies
  Cargo.toml
  build.rs
  contracts/bid/circuits/Cargo.toml
  contracts/bid/circuits/src/correctness.rs
  contracts/transfer/circuits/Cargo.toml
  contracts/transfer/circuits/src/dusk_contract/execute.rs
  contracts/transfer/circuits/src/dusk_contract/send_to_contract_obfuscated.rs
  contracts/transfer/circuits/src/dusk_contract/send_to_contract_transparent.rs
  contracts/transfer/circuits/src/dusk_contract/withdraw_from_obfuscated.rs
  contracts/transfer/circuits/src/dusk_contract/withdraw_from_obfuscated_to_contract.rs
  contracts/transfer/circuits/src/gadgets/commitment.rs
  contracts/transfer/circuits/src/gadgets/merkle.rs
  contracts/transfer/circuits/src/gadgets/nullifier.rs
  contracts/transfer/circuits/src/gadgets/preimage.rs
  contracts/transfer/circuits/src/gadgets/schnorr.rs
  contracts/transfer/circuits/src/gadgets/secret_key.rs
  contracts/transfer/circuits/src/leaf.rs
  contracts/transfer/circuits/src/lib.rs
  src/lib/encoding.rs
  src/lib/services/blindbid.rs
  src/lib/services/blindbid/score_gen_handler.rs
  src/lib/services/blindbid/verify_score_handler.rs
  src/lib/services/pki/stealth_gen.rs
  src/lib/transaction.rs
  tests/blindbid_service.rs
  tests/encoding.rs
  tests/pki_service.rs
Labels: area:conf&build, enhancement, type:feature

#145 Run test setup just once for integration tests
  Cargo.toml
  tests/blindbid_service.rs
  tests/common/encoding.rs
  tests/common/mod.rs
  tests/common/unix.rs
  tests/echo_service_tests.rs
  tests/pki_service.rs
  tests/services/blindbid_service.rs
  tests/services/echo_service.rs
  tests/services/mod.rs
  tests/services/pki_service.rs
  tests/tests.rs
Labels: type:refactor

#142 Custom resolver impl for genesis contracts host fn's
  Cargo.toml
  src/lib/circuit_helpers.rs
  src/lib/lib.rs
  src/lib/ops.rs
  src/lib/ops/errors.rs
  src/lib/ops/hashing.rs
  src/lib/ops/sign.rs
Labels: type:feature
