Repository dusk-network/rusk, pull requests merged in 2022-01, with the labels that each got.

#400 Update circuits to plonk 0.9
  Makefile
  circuits/transfer/Cargo.toml
  circuits/transfer/doc/dusk-genesis-circuits.pdf
  circuits/transfer/src/execute.rs
  circuits/transfer/src/execute/builder.rs
  circuits/transfer/src/execute/crossover.rs
  circuits/transfer/src/execute/input.rs
  circuits/transfer/src/execute/input/signature.rs
  circuits/transfer/src/execute/input/witness.rs
  circuits/transfer/src/execute/output.rs
  circuits/transfer/src/execute/variants.rs
  circuits/transfer/src/gadgets.rs
  circuits/transfer/src/lib.rs
  circuits/transfer/src/send_to_contract_obfuscated.rs
  circuits/transfer/src/send_to_contract_transparent.rs
  circuits/transfer/src/types.rs
  circuits/transfer/src/withdraw_from_obfuscated.rs
  circuits/transfer/src/withdraw_from_transparent.rs
  circuits/transfer/tests/execute.rs
  circuits/transfer/tests/send_to_contract_obfuscated.rs
  circuits/transfer/tests/send_to_contract_transparent.rs
  circuits/transfer/tests/withdraw_from_obfuscated.rs
  circuits/transfer/tests/withdraw_from_transparent.rs
  contracts/stake/Cargo.toml
  contracts/transfer/Cargo.toml
  contracts/transfer/src/transfer/circuits.rs
  contracts/transfer/src/wasm/callable.rs
  contracts/transfer/src/wasm/internal.rs
  contracts/transfer/tests/keys.rs
  contracts/transfer/tests/transfer.rs
  contracts/transfer/tests/wrapper/alice/Cargo.toml
  contracts/transfer/tests/wrapper/mod.rs
  macros/code-hasher/Cargo.toml
  macros/code-hasher/tests/main.rs
  rusk-abi/Cargo.toml
  rusk-abi/src/host.rs
  rusk-abi/tests/contracts/host_fn/Cargo.toml
  rusk-abi/tests/lib.rs
  rusk/Cargo.toml
  rusk/build.rs
  rusk/src/lib/services/pki/stealth_gen.rs
  rusk/tests/services/pki_service.rs
  test-utils/Makefile
Labels: team:Core, mark:testnet

#395 Update kadcast library to release-0.3
  rusk/Cargo.toml
  rusk/src/bin/main.rs
  rusk/src/lib/services/network.rs
Labels: area:p2p, mark:testnet

#416 rusk-abi: Remove unused `rusk-profile` dependency
  rusk-abi/Cargo.toml
Labels: mark:testnet

#414 test-utils: Reinstate tests into CI
  test-utils/Makefile
  test-utils/transfer-wrapper/Cargo.toml
  test-utils/transfer-wrapper/src/lib.rs
Labels: mark:testnet

#415 Enable Clippy in the CI
  .github/workflows/dusk_ci.yml
Labels: mark:testnet

#409 Use `DeriveKey` in WFO/STCO messages
  circuits/transfer/src/send_to_contract_obfuscated.rs
  circuits/transfer/src/types.rs
  circuits/transfer/src/withdraw_from_obfuscated.rs
  circuits/transfer/tests/send_to_contract_obfuscated.rs
  circuits/transfer/tests/withdraw_from_obfuscated.rs
  contracts/transfer/src/transfer/circuits.rs
  contracts/transfer/tests/transfer.rs
  contracts/transfer/tests/wrapper/mod.rs
  rusk/build.rs
Labels: type:tech-debt, module:transfer-contract, module:transfer-circuits, mark:testnet

#432 rusk: Truncate kadcast test messages
  rusk/Cargo.toml
  rusk/src/bin/main.rs
  rusk/src/lib/services/network.rs
Labels: area:testing, mark:testnet

#444 transfer-contract: Update keys
  contracts/transfer/src/transfer/circuits.rs
Labels: module:transfer-contract

#447 Update to Rusk VM 0.8 (release candidate)
  contracts/transfer/Cargo.toml
  rusk-abi/Cargo.toml
  rusk-recovery/Cargo.toml
  rusk-recovery/src/state.rs
  rusk/Cargo.toml
  test-utils/transfer-wrapper/Cargo.toml
Labels: module:transfer-contract, module:rusk-abi, module:rusk, mark:testnet, module:rusk-recovery, module:test-utils

#448 Add TOML config
  rusk/Cargo.toml
  rusk/default.config.toml
  rusk/src/bin/config.rs
  rusk/src/bin/main.rs
  rusk/src/lib/services/network.rs
Labels: mark:testnet

#439 Implement STCT, WFCT, etc... prover services
  rusk/src/lib/services/prover.rs
  rusk/src/lib/services/prover/handler.rs
  rusk/tests/services/prover_service.rs
  schema/prover.proto
Labels: mark:testnet

#456 Bump `rusk-abi` to `0.6.0`
  contracts/stake/Cargo.toml
  contracts/transfer/Cargo.toml
  contracts/transfer/tests/wrapper/alice/Cargo.toml
  contracts/transfer/tests/wrapper/bob/Cargo.toml
  rusk-abi/Cargo.toml
  rusk-abi/tests/contracts/host_fn/Cargo.toml
  test-utils/transfer-wrapper/Cargo.toml
Labels: team:Core, module:rusk-abi, module:rusk-wallet

#453 Provide state query service for a wallet
  contracts/transfer/src/transfer.rs
  rusk-recovery/Cargo.toml
  rusk-recovery/src/state.rs
  rusk/Cargo.toml
  rusk/src/bin/main.rs
  rusk/src/lib/error.rs
  rusk/src/lib/lib.rs
  rusk/src/lib/services/pki.rs
  rusk/src/lib/services/prover.rs
  rusk/src/lib/services/prover/handler.rs
  rusk/src/lib/services/state.rs
  rusk/src/lib/state.rs
  rusk/tests/common/mod.rs
  rusk/tests/services/echo_service.rs
  rusk/tests/services/mod.rs
  rusk/tests/services/pki_service.rs
  rusk/tests/services/prover_service.rs
  rusk/tests/services/state_service.rs
  rusk/tests/tests.rs
  schema/echo.proto
  schema/state.proto
Labels: mark:testnet

#451 Add prove_and_propagate
  rusk/Cargo.toml
  rusk/src/bin/config.rs
  rusk/src/bin/main.rs
  rusk/src/bin/services.rs
  rusk/src/lib/services/network.rs
  rusk/src/lib/services/prover.rs
  rusk/src/lib/services/prover/execute.rs
  rusk/src/lib/services/prover/handler.rs
  rusk/src/lib/services/prover/stco.rs
  rusk/src/lib/services/prover/stct.rs
  rusk/src/lib/services/prover/wfco.rs
  rusk/src/lib/services/prover/wfct.rs
  rusk/tests/services/prover_service.rs
  schema/network.proto
  schema/prover.proto
Labels: mark:testnet

#462 transfer-contract: Validate tx hash
  contracts/transfer/src/transfer.rs
  contracts/transfer/src/transfer/call.rs
  contracts/transfer/src/wasm/callable.rs
  contracts/transfer/src/wasm/internal.rs
  contracts/transfer/tests/wrapper/mod.rs
Labels: mark:testnet

#465 Add a service to get the stake from a public key
  contracts/stake/Cargo.toml
  contracts/stake/src/lib.rs
  contracts/stake/src/wasm.rs
  rusk/Cargo.toml
  rusk/src/lib/error.rs
  rusk/src/lib/lib.rs
  rusk/src/lib/services/state.rs
  rusk/src/lib/state.rs
  rusk/tests/common/mod.rs
  rusk/tests/services/state_service.rs
  schema/state.proto
Labels: team:Core, module:stake-contract, module:rusk, mark:testnet

#471 rusk: Extend the configuration to include rusk-wallet
  rusk/src/bin/config.rs
  rusk/src/bin/config/grpc.rs
  rusk/src/bin/config/kadcast.rs
  rusk/src/bin/config/wallet.rs
  rusk/src/bin/main.rs
Labels: mark:testnet

#476 rusk-abi: Add BLS signature verification
  rusk-abi/Cargo.toml
  rusk-abi/src/module.rs
  rusk-abi/src/module/host.rs
  rusk-abi/src/module/hosted.rs
  rusk-abi/tests/contracts/host_fn/Cargo.toml
  rusk-abi/tests/contracts/host_fn/src/lib.rs
  rusk-abi/tests/lib.rs
Labels: team:Core, mark:testnet

#486 Handle coinbases correctly
  contracts/transfer/Cargo.toml
  contracts/transfer/src/transfer/host.rs
  rusk/src/lib/error.rs
  rusk/src/lib/services/state.rs
  rusk/src/lib/state.rs
Labels: mark:testnet

#487 Initial Preverify implementation
  rusk/src/lib/encoding.rs
  rusk/src/lib/services/state.rs
  schema/state.proto
Labels: mark:testnet

#489 rusk: Serialize tx according to network format
  rusk/src/lib/services.rs
  rusk/src/lib/services/network.rs
  rusk/src/lib/services/state.rs
Labels: mark:testnet

#496 Implement the missing gRPCs
  contracts/stake/Cargo.toml
  contracts/stake/src/contract.rs
  contracts/stake/tests/stake.rs
  rusk/src/lib/services/state.rs
  rusk/src/lib/state.rs
Labels: type:feature, team:Core, module:stake-contract, module:rusk

#454 Wallet CLI
  Cargo.toml
  rusk-wallet/CHANGELOG.md
  rusk-wallet/Cargo.toml
  rusk-wallet/LICENSE
  rusk-wallet/Makefile
  rusk-wallet/build.rs
  rusk-wallet/src/lib/clients.rs
  rusk-wallet/src/lib/crypto.rs
  rusk-wallet/src/lib/error.rs
  rusk-wallet/src/lib/mod.rs
  rusk-wallet/src/lib/prompt.rs
  rusk-wallet/src/lib/store.rs
  rusk-wallet/src/lib/wallet.rs
  rusk-wallet/src/main.rs
Labels: area:wallet, mark:testnet, module:rusk-wallet

#502 Add genesis state
  .gitattributes
  contracts/stake/Cargo.toml
  contracts/stake/src/lib.rs
  contracts/transfer/Cargo.toml
  contracts/transfer/dusk.psk
  contracts/transfer/src/transfer/host.rs
  rusk-recovery/Cargo.toml
  rusk-recovery/provisioners/dusk.0.cpk
  rusk-recovery/src/lib.rs
  rusk-recovery/src/provisioners.rs
  rusk-recovery/src/state.rs
Labels: type:feature, team:Core, module:transfer-contract, module:stake-contract, mark:testnet, module:rusk-recovery

#505 wallet: Add `Export` command
  rusk-wallet/Cargo.toml
  rusk-wallet/src/lib/crypto.rs
  rusk-wallet/src/lib/error.rs
  rusk-wallet/src/lib/mod.rs
  rusk-wallet/src/lib/prompt.rs
  rusk-wallet/src/lib/store.rs
  rusk-wallet/src/lib/wallet.rs
  rusk-wallet/src/main.rs
Labels: area:wallet, team:Core, mark:testnet, module:rusk-wallet

#506 wallet: Add "headless" mode and fix Export in multi-wallet scenarios
  rusk-wallet/CHANGELOG.md
  rusk-wallet/Cargo.toml
  rusk-wallet/src/lib/prompt.rs
  rusk-wallet/src/lib/store.rs
  rusk-wallet/src/lib/wallet.rs
  rusk-wallet/src/main.rs
Labels: area:wallet, mark:testnet, module:rusk-wallet
