Repository dusk-network/rusk, pull requests merged in 2022-11, with the labels that each got.

#768 rusk-recovery: initialize PUB_PARAMS
  rusk-recovery/src/keys.rs
Labels: module:rusk-recovery

#766 Port `transfer-circuits` to `dusk-plonk@0.13`
  Cargo.toml
  circuits/transfer/Cargo.toml
  circuits/transfer/src/error.rs
  circuits/transfer/src/execute.rs
  circuits/transfer/src/execute/builder.rs
  circuits/transfer/src/execute/crossover.rs
  circuits/transfer/src/execute/input.rs
  circuits/transfer/src/execute/output.rs
  circuits/transfer/src/execute/variants.rs
  circuits/transfer/src/gadgets.rs
  circuits/transfer/src/lib.rs
  circuits/transfer/src/send_to_contract_obfuscated.rs
  circuits/transfer/src/send_to_contract_transparent.rs
  circuits/transfer/src/types.rs
  circuits/transfer/src/withdraw_from_obfuscated.rs
  circuits/transfer/src/withdraw_from_transparent.rs
  circuits/transfer/tests/execute.rs
  circuits/transfer/tests/keys/mod.rs
  circuits/transfer/tests/send_to_contract_obfuscated.rs
  circuits/transfer/tests/send_to_contract_transparent.rs
  circuits/transfer/tests/withdraw_from_obfuscated.rs
  circuits/transfer/tests/withdraw_from_transparent.rs
  macros/code-hasher/Cargo.toml
  macros/code-hasher/src/lib.rs
  macros/code-hasher/tests/main.rs
  rusk-abi/Cargo.toml
  rusk-recovery/Cargo.toml
  rusk-recovery/src/keys.rs
  rusk-recovery/src/keys/transfer.rs
Labels: type:enhancement, team:Core

#769 stake-contract: Remove `allowlist` field
  .github/workflows/dusk_ci.yml
  contracts/stake/src/contract.rs
  contracts/stake/src/wasm.rs
  contracts/stake/tests/stake.rs
Labels: mark:testnet
